server:
  port: 1001

spring:
  application:
    name: zull-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2222/eureka/

zuul:
  routes:

    路由1:
      path: /p/**
      service-id: producer-server
      strip-prefix: true

    路由2:
      path: /c/**
      service-id: consumer-server
      strip-prefix: true