server:
  port: 0

spring:
  application:
    name: admin-server

eureka:
  client:
    service-url:
      defaultZone: http://www.yihiyi.cn:2000/eureka/

logging:
  file:
    name: ../mylogs/${spring.application.name}.log
