server:
  port: 2000

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}:${spring.application.name}

  client:
    register-with-eureka: false  #false:不作为一个客户端注册到注册中心
    fetch-registry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  file:
    name: ../mylogs/${spring.application.name}.log