server:
  port: 1001

spring:
  application:
    name: zull-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka/

logging:
  file:
    name: ../mylogs/${spring.application.name}.log

zuul:
  routes:

    route1:
      path: /p/**
      service-id: producer-server
      strip-prefix: true

    route2:
      path: /c/**
      service-id: consumer-server
      strip-prefix: true